name: "Submit a Level"
description: "Share a new level."
labels: [level-submission, pending]
title: "[Level] <Name>"
body:
  - type: input
    id: level_name
    attributes: { label: Level Name }
    validations: { required: true }
  - type: textarea
    id: description
    attributes: { label: Level Description }
    validations: { required: true }
  - type: textarea
    id: level_code
    attributes: { label: Level Code (paste the full text) }
    validations: { required: true }
  - type: input
    id: creator
    attributes: { label: Creator (optional) }
