name: "Submit a Level"
description: "Share a new level for the Course World."
labels: [level-submission, pending]
title: "[Level] <Give your level a short name>"
body:
- type: input
id: level_name
attributes:
label: Level Name
description: Display name for your level
placeholder: e.g., Sky Spikes 1-1
validations:
required: true
- type: textarea
id: description
attributes:
label: Level Description
description: What should players know?
placeholder: Short description, tips, creator credits
validations:
required: true
- type: textarea
id: level_code
attributes:
label: Level Code (Paste the code used by the game)
description: Paste the **full level text/code** your game consumes.
placeholder: Paste your level code here
render: text
validations:
required: true
- type: input
id: creator
attributes:
label: Creator (optional)
placeholder: your handle (optional)
validations:
required: false
